version: '2'
services:

    web:
        build: ./
        volumes:
            - ./:/var/www/html/
        links:
            - db
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "<YOUR GITHUB API TOKEN>"


        # For Apache based image:
        ports:
            - "8080:80"

        # For FPM/HHVM based image:
        #expose:
        #    - "9000"

        # Autostart at boottime
        #restart: always

        # Send log output to syslog
        #logging:
        #    driver: "syslog"
        #    options:
        #        tag: "docker-web"

    # For FPM/HHVM based image:
    #nginx:
    #    build:
    #       context: .
    #       dockerfile: Dockerfile
    #    restart: always
    #    ports:
    #        - "8080:80"
    #    links:
    #        - web
    #    volumes_from:
    #        - web


    db:
        image: mongo:3
        container_name: db
        expose:
            - "27017"
        volumes:
            - mongo:/data/db

        # Autostart at boottime
        #restart: always

