#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(dirname(__FILE__) . 'helpers/DockerEnv.php');
\DockerEnv::init();
$config = \DockerEnv::consoleConfig();

$application = new yii\console\Application($config);

\Yii::setAlias('@bower', $application->vendorPath . DIRECTORY_SEPARATOR . 'bower-asset');

$exitCode = $application->run();

exit($exitCode);
