<?php

return [
    ["code" => "AUD", "title" => "Australia Dollar"],
    ["code" => "BGN", "title" => "Bulgaria Lev"],
    ["code" => "BRL", "title" => "Brazil Real"],
    ["code" => "CAD", "title" => "Canada Dollar"],
    ["code" => "CHF", "title" => "Switzerland Franc"],
    ["code" => "CNY", "title" => "China Yuan Renminbi"],
    ["code" => "CZK", "title" => "Czech Republic Koruna"],
    ["code" => "DKK", "title" => "Denmark Krone"],
    ["code" => "EUR", "title" => "Euro Member Countries"],
    ["code" => "GBP", "title" => "United Kingdom Pound"],
    ["code" => "HKD", "title" => "Hong Kong Dollar"],
    ["code" => "HRK", "title" => "Croatia Kuna"],
    ["code" => "HUF", "title" => "Hungary Forint"],
    ["code" => "IDR", "title" => "Indonesia Rupiah"],
    ["code" => "ILS", "title" => "Israel Shekel"],
    ["code" => "INR", "title" => "India Rupee"],
    ["code" => "JPY", "title" => "Japan Yen"],
    ["code" => "KRW", "title" => "Korea (South) Won"],
    ["code" => "MXN", "title" => "Mexico Peso"],
    ["code" => "MYR", "title" => "Malaysia Ringgit"],
    ["code" => "NOK", "title" => "Norway Krone"],
    ["code" => "NZD", "title" => "New Zealand Dollar"],
    ["code" => "PHP", "title" => "Philippines Peso"],
    ["code" => "PLN", "title" => "Poland Zloty"],
    ["code" => "RON", "title" => "Romania Leu"],
    ["code" => "RUB", "title" => "Russia Ruble"],
    ["code" => "SEK", "title" => "Sweden Krona"],
    ["code" => "SGD", "title" => "Singapore Dollar"],
    ["code" => "THB", "title" => "Thailand Baht"],
    ["code" => "TRY", "title" => "Turkey Lira"],
    ["code" => "USD", "title" => "United States Dollar"],
    ["code" => "ZAR", "title" => "South Africa Rand"]
];